/***************************************************************
 *
 *           This code is part the Piano Notes WebApp
 *
 * Copyrights 2026 - Varanda Labs Inc.
 *
 * License: GPL-v3
 *   https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 *
 ***************************************************************
 */

export { NOTES_TABLE }

const NOTES_TABLE = [
  { 'note': 'A0', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#0', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 131}, 
  { 'note': 'B0', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C1', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C#1', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 407}, 
  { 'note': 'D1', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'D#1', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 589}, 
  { 'note': 'E1', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F1', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F#1', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 868}, 
  { 'note': 'G1', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'G#1', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 1036},
  { 'note': 'A1', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#1', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 1203}, 
  { 'note': 'B1', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C2', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C#2', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 1479}, 
  { 'note': 'D2', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'D#2', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 1661}, 
  { 'note': 'E2', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F2', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F#2', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 1940}, 
  { 'note': 'G2', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'G#2', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 2108},
  { 'note': 'A2', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#2', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 2275}, 
  { 'note': 'B2', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C3', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C#3', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 2551}, 
  { 'note': 'D3', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'D#3', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 2733}, 
  { 'note': 'E3', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F3', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F#3', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 3012}, 
  { 'note': 'G3', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'G#3', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 3180},
  { 'note': 'A3', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#3', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 3347}, 
  { 'note': 'B3', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C4', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C#4', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 3623}, 
  { 'note': 'D4', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'D#4', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 3805}, 
  { 'note': 'E4', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F4', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F#4', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 4084}, 
  { 'note': 'G4', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'G#4', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 4252},
  { 'note': 'A4', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#4', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 4419}, 
  { 'note': 'B4', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C5', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C#5', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 4695}, 
  { 'note': 'D5', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'D#5', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 4877}, 
  { 'note': 'E5', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F5', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F#5', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 5156}, 
  { 'note': 'G5', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'G#5', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 5324},
  { 'note': 'A5', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#5', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 5491}, 
  { 'note': 'B5', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C6', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C#6', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 5767}, 
  { 'note': 'D6', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'D#6', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 5949}, 
  { 'note': 'E6', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F6', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F#6', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 6228}, 
  { 'note': 'G6', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'G#6', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 6396},
  { 'note': 'A6', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#6', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 6563}, 
  { 'note': 'B6', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C7', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C#7', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 6839}, 
  { 'note': 'D7', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'D#7', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 7021}, 
  { 'note': 'E7', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F7', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'F#7', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 7300}, 
  { 'note': 'G7', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'G#7', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 7468},
  { 'note': 'A7', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'A#7', 'is_black': true, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 7635}, 
  { 'note': 'B7', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}, 
  { 'note': 'C8', 'is_black': false, 'flat': '', 'solfege': '', 'solfege_flat': '', 'x': 0}
];