/***************************************************************
 *
 *           This code is part the Piano Notes WebApp
 *
 * Copyrights 2026 - Varanda Labs Inc.
 *
 * License: GPL-v3
 *   https://www.gnu.org/licenses/gpl-3.0.en.html
 *
 *
 ***************************************************************
 */

export { NOTES_TABLE }

const NOTES_TABLE = [
  { 'note': 'A0', 'is_black': false, 'flat': '',    'solfege': 'La0', 'solfege_flat': '',      'x': 0}, 
  { 'note': 'A#0', 'is_black': true, 'flat': 'Bb0', 'solfege': 'La#0', 'solfege_flat': 'Sib0', 'x': 131}, 
  { 'note': 'B0', 'is_black': false, 'flat': '',    'solfege': 'Si0',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C1', 'is_black': false, 'flat': '',    'solfege': 'Do1',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C#1', 'is_black': true, 'flat': 'Db1', 'solfege': 'Do#1', 'solfege_flat': 'Reb1', 'x': 407}, 
  { 'note': 'D1', 'is_black': false, 'flat': '',    'solfege': 'Re1',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'D#1', 'is_black': true, 'flat': 'Eb1', 'solfege': 'Re#1', 'solfege_flat': 'Mib1', 'x': 589}, 
  { 'note': 'E1', 'is_black': false, 'flat': '',    'solfege': 'Mi1',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F1', 'is_black': false, 'flat': '',    'solfege': 'Fa1',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F#1', 'is_black': true, 'flat': 'Gb1', 'solfege': 'Fa#1', 'solfege_flat': 'Solb1','x': 868}, 
  { 'note': 'G1', 'is_black': false, 'flat': '',    'solfege': 'Sol1', 'solfege_flat': '',     'x': 0}, 
  { 'note': 'G#1', 'is_black': true, 'flat': 'Ab1', 'solfege': 'Sol#1','solfege_flat': 'Lab1', 'x': 1036},
  { 'note': 'A1', 'is_black': false, 'flat': '',    'solfege': 'La1',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'A#1', 'is_black': true, 'flat': 'Bb1', 'solfege': 'La#1', 'solfege_flat': 'Sib1', 'x': 1203}, 
  { 'note': 'B1', 'is_black': false, 'flat': '',    'solfege': 'Si1',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C2', 'is_black': false, 'flat': '',    'solfege': 'Do2',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C#2', 'is_black': true, 'flat': 'Db2', 'solfege': 'Do#2', 'solfege_flat': 'Reb2', 'x': 1479}, 
  { 'note': 'D2', 'is_black': false, 'flat': '',    'solfege': 'Re2',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'D#2', 'is_black': true, 'flat': 'Eb2', 'solfege': 'Re#2', 'solfege_flat': 'Mib2', 'x': 1661}, 
  { 'note': 'E2', 'is_black': false, 'flat': '',    'solfege': 'Mi2',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F2', 'is_black': false, 'flat': '',    'solfege': 'Fa2',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F#2', 'is_black': true, 'flat': 'Gb2', 'solfege': 'Fa#2', 'solfege_flat': 'Solb2','x': 1940}, 
  { 'note': 'G2', 'is_black': false, 'flat': '',    'solfege': 'Sol2', 'solfege_flat': '',     'x': 0}, 
  { 'note': 'G#2', 'is_black': true, 'flat': 'Ab2', 'solfege': 'Sol#2','solfege_flat': 'Lab2', 'x': 2108},
  { 'note': 'A2', 'is_black': false, 'flat': '',    'solfege': 'La2',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'A#2', 'is_black': true, 'flat': 'Bb2', 'solfege': 'La#2', 'solfege_flat': 'Sib2', 'x': 2275}, 
  { 'note': 'B2', 'is_black': false, 'flat': '',    'solfege': 'Si2',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C3', 'is_black': false, 'flat': '',    'solfege': 'Do3',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C#3', 'is_black': true, 'flat': 'Db3', 'solfege': 'Do#3', 'solfege_flat': 'Reb3', 'x': 2551}, 
  { 'note': 'D3', 'is_black': false, 'flat': '',    'solfege': 'Re3',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'D#3', 'is_black': true, 'flat': 'Eb3', 'solfege': 'Re#3', 'solfege_flat': 'Mib3', 'x': 2733}, 
  { 'note': 'E3', 'is_black': false, 'flat': '',    'solfege': 'Mi3',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F3', 'is_black': false, 'flat': '',    'solfege': 'Fa3',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F#3', 'is_black': true, 'flat': 'Gb3', 'solfege': 'Fa#3', 'solfege_flat': 'Solb3','x': 3012}, 
  { 'note': 'G3', 'is_black': false, 'flat': '',    'solfege': 'Sol3', 'solfege_flat': '',     'x': 0}, 
  { 'note': 'G#3', 'is_black': true, 'flat': 'Ab3', 'solfege': 'Sol#3','solfege_flat': 'Lab3', 'x': 3180},
  { 'note': 'A3', 'is_black': false, 'flat': '',    'solfege': 'La3',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'A#3', 'is_black': true, 'flat': 'Bb3', 'solfege': 'La#3', 'solfege_flat': 'Sib3', 'x': 3347}, 
  { 'note': 'B3', 'is_black': false, 'flat': '',    'solfege': 'Si3',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C4', 'is_black': false, 'flat': '',    'solfege': 'Do4',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C#4', 'is_black': true, 'flat': 'Db4', 'solfege': 'Do#4', 'solfege_flat': 'Reb4', 'x': 3623}, 
  { 'note': 'D4', 'is_black': false, 'flat': '',    'solfege': 'Re4',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'D#4', 'is_black': true, 'flat': 'Eb4', 'solfege': 'Re#4', 'solfege_flat': 'Mib4', 'x': 3805}, 
  { 'note': 'E4', 'is_black': false, 'flat': '',    'solfege': 'Mi4',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F4', 'is_black': false, 'flat': '',    'solfege': 'Fa4',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F#4', 'is_black': true, 'flat': 'Gb4', 'solfege': 'Fa#4', 'solfege_flat': 'Solb4','x': 4084}, 
  { 'note': 'G4', 'is_black': false, 'flat': '',    'solfege': 'Sol4', 'solfege_flat': '',     'x': 0}, 
  { 'note': 'G#4', 'is_black': true, 'flat': 'Ab4', 'solfege': 'Sol#4','solfege_flat': 'Lab4', 'x': 4252},
  { 'note': 'A4', 'is_black': false, 'flat': '',    'solfege': 'La4',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'A#4', 'is_black': true, 'flat': 'Bb4', 'solfege': 'La#4', 'solfege_flat': 'Sib4', 'x': 4419}, 
  { 'note': 'B4', 'is_black': false, 'flat': '',    'solfege': 'Si4',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C5', 'is_black': false, 'flat': '',    'solfege': 'Do5',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C#5', 'is_black': true, 'flat': 'Db5', 'solfege': 'Do#5', 'solfege_flat': 'Reb5', 'x': 4695}, 
  { 'note': 'D5', 'is_black': false, 'flat': '',    'solfege': 'Re5',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'D#5', 'is_black': true, 'flat': 'Eb5', 'solfege': 'Re#5', 'solfege_flat': 'Mib5', 'x': 4877}, 
  { 'note': 'E5', 'is_black': false, 'flat': '',    'solfege': 'Mi5',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F5', 'is_black': false, 'flat': '',    'solfege': 'Fa5',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F#5', 'is_black': true, 'flat': 'Gb5', 'solfege': 'Fa#5', 'solfege_flat': 'Solb5','x': 5156}, 
  { 'note': 'G5', 'is_black': false, 'flat': '',    'solfege': 'Sol5', 'solfege_flat': '',     'x': 0}, 
  { 'note': 'G#5', 'is_black': true, 'flat': 'Ab5', 'solfege': 'Sol#5','solfege_flat': 'Lab5', 'x': 5324},
  { 'note': 'A5', 'is_black': false, 'flat': '',    'solfege': 'La5',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'A#5', 'is_black': true, 'flat': 'Bb5', 'solfege': 'La#5', 'solfege_flat': 'Sib5', 'x': 5491}, 
  { 'note': 'B5', 'is_black': false, 'flat': '',    'solfege': 'Si5',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C6', 'is_black': false, 'flat': '',    'solfege': 'Do6',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C#6', 'is_black': true, 'flat': 'Db6', 'solfege': 'Do#6', 'solfege_flat': 'Reb6', 'x': 5767}, 
  { 'note': 'D6', 'is_black': false, 'flat': '',    'solfege': 'Re6',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'D#6', 'is_black': true, 'flat': 'Eb6', 'solfege': 'Re#6', 'solfege_flat': 'Mib6', 'x': 5949}, 
  { 'note': 'E6', 'is_black': false, 'flat': '',    'solfege': 'Mi6',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F6', 'is_black': false, 'flat': '',    'solfege': 'Fa6',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F#6', 'is_black': true, 'flat': 'Gb6', 'solfege': 'Fa#6', 'solfege_flat': 'Solb6','x': 6228}, 
  { 'note': 'G6', 'is_black': false, 'flat': '',    'solfege': 'Sol6', 'solfege_flat': '',     'x': 0}, 
  { 'note': 'G#6', 'is_black': true, 'flat': 'Ab6', 'solfege': 'Sol#6','solfege_flat': 'Lab6', 'x': 6396},
  { 'note': 'A6', 'is_black': false, 'flat': '',    'solfege': 'La6',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'A#6', 'is_black': true, 'flat': 'Bb6', 'solfege': 'La#6', 'solfege_flat': 'Sib6', 'x': 6563}, 
  { 'note': 'B6', 'is_black': false, 'flat': '',    'solfege': 'Si6',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C7', 'is_black': false, 'flat': '',    'solfege': 'Do7',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C#7', 'is_black': true, 'flat': 'Db7', 'solfege': 'Do#7', 'solfege_flat': 'Reb7', 'x': 6839}, 
  { 'note': 'D7', 'is_black': false, 'flat': '',    'solfege': 'Re7',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'D#7', 'is_black': true, 'flat': 'Eb7', 'solfege': 'Re#7', 'solfege_flat': 'Mib7', 'x': 7021}, 
  { 'note': 'E7', 'is_black': false, 'flat': '',    'solfege': 'Mi7',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F7', 'is_black': false, 'flat': '',    'solfege': 'Fa7',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'F#7', 'is_black': true, 'flat': 'Gb7', 'solfege': 'Fa#7', 'solfege_flat': 'Solb7','x': 7300}, 
  { 'note': 'G7', 'is_black': false, 'flat': '',    'solfege': 'Sol7', 'solfege_flat': '',     'x': 0}, 
  { 'note': 'G#7', 'is_black': true, 'flat': 'Ab7', 'solfege': 'Sol#7','solfege_flat': 'Lab7', 'x': 7468},
  { 'note': 'A7', 'is_black': false, 'flat': '',    'solfege': 'La7',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'A#7', 'is_black': true, 'flat': 'Bb7', 'solfege': 'La#7', 'solfege_flat': 'Sib7', 'x': 7635}, 
  { 'note': 'B7', 'is_black': false, 'flat': '',    'solfege': 'Si7',  'solfege_flat': '',     'x': 0}, 
  { 'note': 'C8', 'is_black': false, 'flat': '',    'solfege': 'Do8',  'solfege_flat': '',     'x': 0}
];